# Generated by Django 4.1 on 2022-08-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytodo',
            old_name='complete_date',
            new_name='completed',
        ),
    ]
